### ISSUE TITLE
Exit code 0 even when errors are found

### ISSUE THREAD

**Issue by kimmobrunfeldt** [gburgett/linkscanner#118]
Exit code 0 indicates success. I think when broken links are found, the CLI should with non-zero value: `process.exit(nonZeroValue)` to indicate errors. This would allow using the CLI tool in a CI pipeline.

**Comment by gburgett** [comment]
Hi!  I appreciate the feedback!

I would consider adding a `--fail` switch to opt in to this behavior.  I'd love for this tool to be as similar as possible to cURL for command line switches.

Would you consider sending a pull request to add that switch?

**Comment by kimmobrunfeldt** [comment]
I ended up using https://github.com/JustinBeckwith/linkinator. Thanks for taking the time to reply in any case :+1:
